#!/usr/bin/env bun
// gen-digest.ts [--check]   regenerate skills/ds-rules/SKILL.md from the canonical DS rule files.
//
// The digest is DERIVED: the four aggregates under skills/ds/rules/ name every id, and each id's
// rule file under rules/ holds the text. Per rule this keeps, from the `## Rule` section (or the
// `**Rule.**` lead when a file has none): the first prose paragraph, every bold-led or must/never
// paragraph, every list and table, and a lead-in ending in ':' before one. Code blocks, rationale
// and examples stay in the canonical file.
// --check exits 1 when the committed SKILL.md differs from a fresh generation.
import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const SKILL_DIR = join(dirname(fileURLToPath(import.meta.url)), '..')
const ROOT = join(SKILL_DIR, '..', '..')
const OUT = join(SKILL_DIR, 'SKILL.md')
const AGGREGATES = ['ds-common-constraints', 'ds-common-conventions', 'ds-analysis-constraints', 'ds-engineering-constraints']

const stripFrontmatter = (s: string) => s.replace(/^---\n[\s\S]*?\n---\n/, '')
const stripCode = (s: string) => s.replace(/^```[\s\S]*?^```\s*$/gm, '')

/** The normative part of one rule file. */
export function extractRule(md: string): string {
  const body = stripCode(stripFrontmatter(md)).replace(/^<\/?[A-Z-]+>\s*$/gm, '')
  const lines = body.split('\n')
  let start = lines.findIndex(l => /^## (Rule\b|The Iron Law)/.test(l))
  if (start === -1) start = lines.findIndex(l => /^# /.test(l))
  if (start === -1) throw new Error('no `## Rule` section and no H1 to lead from')
  let end = lines.findIndex((l, i) => i > start && /^## /.test(l))
  if (end === -1) end = lines.length
  const paras = lines.slice(start + 1, end).join('\n').split(/\n\s*\n/).map(p => p.trim()).filter(Boolean)
  const kept: string[] = []
  let prose = false
  for (const [i, p] of paras.entries()) {
    if (/^#/.test(p)) continue
    // A kept lead-in ending in ':' introduces what follows; keep the list it introduces.
    if (p.endsWith(':') && /^(-|\d+\.|\|) /.test(paras[i + 1] ?? '')) { kept.push(p); continue }
    if (p.startsWith('|')) { kept.push(p); continue }
    if (p.startsWith("**") || /\b(MUST|NEVER|must|never)\b/.test(p)) { kept.push(p); prose = true; continue }
    if (/^(-|\d+\.) /.test(p)) { kept.push(p); continue }
    if (!prose && !p.startsWith('-')) { kept.push(p); prose = true }
  }
  return kept.join('\n\n')
}

type Entry = { id: string; title: string; summary: string; file: string }

export function indexEntries(): Entry[] {
  const out: Entry[] = []
  for (const agg of AGGREGATES) {
    const md = readFileSync(join(ROOT, 'skills', 'ds', 'rules', `${agg}.md`), 'utf8')
    for (const m of md.matchAll(/^\| ([CVAE]\d+) \| ([^|]+?) \| \[[^\]]+\]\(\$\{CLAUDE_PLUGIN_ROOT\}\/(rules\/[\w.-]+\.md)\) \| (.+?) \|$/gm)) {
      out.push({ id: m[1], title: m[2], file: m[3], summary: m[4] })
    }
  }
  return out
}

export function generate(): string {
  const entries = indexEntries()
  const sections = entries.map(e =>
    `### ${e.id} — ${e.title}\n\n_${e.summary}_ (\`${e.file}\`)\n\n${extractRule(readFileSync(join(ROOT, e.file), 'utf8'))}`)
  return `---
name: ds-rules
description: "The DS constraints C1-C6, V1-V9, A1-A6, E1-E7 as binding rule statements. Preloaded by the ds and ds-reviewer agents; load it before any data, table or figure work that is not running inside one."
---

<!-- GENERATED by skills/ds-rules/scripts/gen-digest.ts from skills/ds/rules/*.md and the rules/ files they index. Do not edit; edit the canonical file and regenerate. -->

# DS rules (${entries.length})

These are binding on every data task, however you were launched. Each entry is the rule statement
from its canonical file under \`\${CLAUDE_PLUGIN_ROOT}/\`; open that file for the rationale, the
examples and the checker that enforces it. When this skill is invoked with arguments, they are your
task: do it under these rules.

${sections.join('\n\n')}
`
}

if (import.meta.main) {
  const fresh = generate()
  if (process.argv.includes('--check')) {
    const cur = readFileSync(OUT, 'utf8')
    if (cur !== fresh) { console.error('ds-rules digest is STALE: run bun skills/ds-rules/scripts/gen-digest.ts'); process.exit(1) }
    console.log('ds-rules digest is current')
  } else {
    writeFileSync(OUT, fresh)
    console.log(`wrote ${OUT} (${fresh.length} chars, ~${Math.round(fresh.length / 4)} tokens)`)
  }
}
