// `load-constraints <scope> --digest` is what the ds-rules skill bang-loads into the ds agents. It
// replaced a committed digest generated by skills/ds-rules/scripts/gen-digest.ts; the pinned-tree
// tests prove the loader prints exactly the rule sections that digest committed, on the corpus it
// was committed from, so the deletion lost nothing.
import { test, expect } from 'bun:test'
import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { spawnSync } from 'node:child_process'
import { digestEntries } from '../scripts/load-constraints.ts'
import { useTmp } from './helpers/tmp.ts'

const mkTmp = useTmp()
const ROOT = join(import.meta.dir, '..')
const LOADER = join(ROOT, 'scripts', 'load-constraints')
const run = (...args: string[]) => spawnSync(LOADER, args, { encoding: 'utf8', timeout: 30_000 })
const git = (...args: string[]) => spawnSync('git', ['-C', ROOT, ...args], { encoding: 'utf8', timeout: 30_000, maxBuffer: 1 << 26 })

// The last two commits that carried skills/ds-rules/SKILL.md as a committed digest.
for (const [label, sha] of [['v6.39.0', '58bf57eb'], ['v6.40.1', '106f4ef3']]) {
  test(`--digest reproduces the ${label} committed digest's rule sections on that commit's corpus`, () => {
    const tree = mkTmp('ds-digest-pinned-')
    const files = git('ls-tree', '-r', '--name-only', sha, '--', 'rules', 'skills/ds/rules')
    expect(files.status).toBe(0)
    for (const f of files.stdout.trim().split('\n')) {
      mkdirSync(join(tree, f, '..'), { recursive: true })
      writeFileSync(join(tree, f), git('show', `${sha}:${f}`).stdout)
    }
    const committed = git('show', `${sha}:skills/ds-rules/SKILL.md`)
    expect(committed.status).toBe(0)
    const rendered = committed.stdout.replaceAll('${CLAUDE_PLUGIN_ROOT}', tree)
    const want = rendered.slice(rendered.indexOf('\n### ') + 1)
    const out = run('ds', '--digest', '--dir', join(tree, 'rules'))
    expect(out.status).toBe(0)
    expect(out.stdout.split('\n')[0]).toBe('# Rule digest for ds (28)')
    expect(out.stdout.slice(out.stdout.indexOf('\n### ') + 1)).toBe(want)
  })
}

test('the live ds digest carries every indexed id, each with a rule statement', () => {
  const ids = digestEntries('ds', ROOT).map(e => e.id)
  expect(ids.length).toBe(28)
  expect([...new Set(ids.map(i => i[0]))]).toEqual(['C', 'V', 'A', 'E'])
  const out = run('ds', '--digest')
  expect(out.status).toBe(0)
  expect(out.stdout).not.toContain('${CLAUDE_PLUGIN_ROOT}')
  for (const id of ids) {
    const body = out.stdout.split(new RegExp(`^### ${id} — .*$`, 'm'))[1]?.split(/^### /m)[0] ?? ''
    expect(body.replace(/^_.*_ \(`.*`\)$/m, '').trim().length).toBeGreaterThan(40)
  }
})

test('a rule edit reaches the digest with no regeneration step', () => {
  const tree = mkTmp('ds-digest-live-')
  mkdirSync(join(tree, 'rules'))
  mkdirSync(join(tree, 'skills', 'x', 'rules'), { recursive: true })
  writeFileSync(join(tree, 'skills', 'x', 'rules', 'agg.md'),
    '---\nname: agg\napplies-to: [x]\n---\n\n| ID | Constraint | File | Description |\n|----|----|----|----|\n| X1 | One | [r.md](${CLAUDE_PLUGIN_ROOT}/rules/r.md) | the summary |\n')
  const rule = (s: string) => writeFileSync(join(tree, 'rules', 'r.md'), `---\nname: r\napplies-to: [x-delegate]\n---\n# r\n\n## Rule\n\n${s}\n\n## Why\n\nrationale\n`)
  rule('Always do the first thing.')
  expect(run('x', '--digest', '--dir', join(tree, 'rules')).stdout).toContain('Always do the first thing.')
  rule('Always do the second thing.')
  const out = run('x', '--digest', '--dir', join(tree, 'rules')).stdout
  expect(out).toContain('Always do the second thing.')
  expect(out).not.toContain('rationale')
})

test('a scope whose aggregates index nothing is exit 2 and says NO digest, never an empty one', () => {
  const out = run('no-such-scope', '--digest')
  expect(out.status).toBe(2)
  expect(out.stdout).toBe('')
  expect(out.stderr).toContain('NO rule digest')
})
