#!/usr/bin/env -S uv run --with lxml,pyyaml,pytest python3
"""Tests for scripts/prose-audit.py — the single deterministic prose/AI audit.

What is worth testing here is exactly what the consolidation promised and the four previous
loaders could not do:

  * ONE entry point covers every pattern system (scored tics, wikipedia-*, diction, stylometrics,
    the domain style guides);
  * overlapping hits COLLAPSE into one span at the highest contributing severity — the phrase
    `rich tapestry` reported three times under three labels is the bug this replaced;
  * the provenance-leak class is CAUGHT — `de_ai_audit.py`, the one script the prose reviewer was
    pointed at, missed every one of the seven artifacts asserted below;
  * all three document formats work, and footnotes are masked in each of them.

Run:  uv run --with lxml,pyyaml,pytest python3 -m pytest tests/test_prose_audit.py
"""
from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
AUDIT_PATH = REPO_ROOT / "scripts" / "prose-audit.py"
FIXTURES = REPO_ROOT / "tests" / "fixtures" / "prose-audit"


def _load():
    spec = importlib.util.spec_from_file_location("prose_audit", AUDIT_PATH)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


PA = _load()


# The .docx fixture is BUILT, not committed: a tracked binary needs a reviewed disposition in a
# candidate manifest (scripts/scan-public-privacy.ts), and generated bytes are reviewable besides.
_DOCX_BUILDER = importlib.util.spec_from_file_location("build_docx", FIXTURES / "build_docx.py")
_BUILD = importlib.util.module_from_spec(_DOCX_BUILDER)
_DOCX_BUILDER.loader.exec_module(_BUILD)
_DOCX = Path(tempfile.mkdtemp(prefix="prose-audit-fixture-")) / "manuscript.docx"
_BUILD.build(_DOCX)


def _fixture(name: str) -> Path:
    return _DOCX if name.endswith(".docx") else FIXTURES / name


def _audit(name: str, style: str | None = None) -> dict:
    return PA.audit_document(_fixture(name), style=style)


def _labels(res: dict) -> str:
    return " ".join(lab for s in res["spans"] for lab in s["labels"])


# ── C1: one entry point covers all five systems ──────────────────────────────
def test_every_pattern_system_is_represented():
    res = _audit("tics.md", style="legal")
    systems = {s["system"] for s in res["spans"]} | {
        sys_ for s in res["spans"] for sys_ in s["systems"]}
    for expected in ("scored-tic", "wikipedia-puffery", "wikipedia-promotional",
                     "wikipedia-communication", "wikipedia-chatgpt-artifacts",
                     "diction", "style", "writing-legal"):
        assert expected in systems, f"{expected} missing from {sorted(systems)}"


def test_domain_guide_is_gated_by_style():
    """Volokh is legal-only. Loading it for every draft is what the domain gate exists to stop."""
    general = {s["system"] for s in _audit("tics.md")["spans"]}
    legal = {s["system"] for s in _audit("tics.md", style="legal")["spans"]}
    assert "writing-legal" not in general
    assert "writing-legal" in legal


# ── C2: overlaps collapse ────────────────────────────────────────────────────
def test_overlap_collapses():
    """`rich tapestry` matches the sev4 scored tic, wikipedia-promotional AND diction always_flag.
    Before the consolidation that was three findings with three severities. It is one span."""
    res = _audit("tics.md")
    hits = [s for s in res["spans"] if s["quote"].lower() == "rich tapestry"]
    assert len(hits) == 1, hits
    span = hits[0]
    assert any("wikipedia-promotional" in lab for lab in span["labels"]), span["labels"]
    assert any("ai-tic·sev4·rich-tapestry" in lab for lab in span["labels"]), span["labels"]
    # Highest contributing severity wins: the scored tic is hard, the other two are soft.
    assert span["severity"] == "hard", span
    # The plain replacement survives the merge even though it came from the soft contributor.
    assert span["replace_with"], span


def test_unrelated_findings_on_one_line_stay_separate():
    """Collapse is by OVERLAPPING COLUMN RANGE, not by line. Two distinct phrases on the same
    line are two findings, and merging them would hide one."""
    res = _audit("tics.md")
    line3 = [s for s in res["spans"] if s["line"] == 3]
    assert len(line3) == 2, line3
    assert {s["quote"] for s in line3} == {"stands as a testament to", "nestled"}


def test_cluster_diction_columns_are_line_relative(tmp_path):
    """A cluster-tier match is found in the whole PARAGRAPH, so its offset must be converted back
    to a column within its own line. It was not, so every match past the paragraph's first line
    landed at a column beyond the end of that line — mislocating the span AND, worse, silently
    missing the overlap with any other system that reported the same words at their real column."""
    draft = tmp_path / "cluster.md"
    draft.write_text("The board will galvanize the committee and\n"
                     "harness the cutting-edge disclosure regime today.\n")
    res = PA.audit_document(draft)
    hit = next(s for s in res["spans"] if any("cutting-edge" in lab for lab in s["labels"]))
    assert hit["line"] == 2
    assert hit["col"] == 13, hit          # "harness the cutting-edge…"
    # …and because the column is right, it collapses with wikipedia-promotional's own match.
    assert "wikipedia-promotional" in hit["systems"], hit
    assert len([s for s in res["spans"] if "cutting-edge" in s["quote"]]) == 1


def test_span_ids_are_stable_and_in_document_order():
    res = _audit("tics.md")
    assert [s["id"] for s in res["spans"]] == [f"S{i:03d}" for i in range(1, len(res["spans"]) + 1)]
    lines = [s["line"] for s in res["spans"] if s["line"]]
    assert lines == sorted(lines)
    # Same input, same ids — a reviewer citing S003 must mean the same span on a re-run.
    assert [s["id"] for s in _audit("tics.md")["spans"]] == [s["id"] for s in res["spans"]]


# ── C3: the coverage gap de_ai_audit.py left ─────────────────────────────────
# Every one of these was MISSED by de_ai_audit.py on this fixture, and de_ai_audit.py is the only
# scorer user-agents/writing-reviewer.md ever pointed at. Four of the seven are hard.
_ARTIFACTS = [
    ("As an AI language model", "hard"),
    ("I hope this helps", "hard"),
    ("citeturn0search0", "hard"),
    ("oaicite", "hard"),
    ("stands as a testament", "hard"),   # sev4 scored tic
    # `plays a vital role` was here at soft. It is REJECTED in tics.yaml at 122 hits / 21.94/M —
    # the bare form is human prose and only `plays a pivotal role in shaping` cleared the gate — so
    # the row asserted the defect. `nestled` replaces it: same table, same severity, gate-clean at
    # 0.2/M in diction.yaml.
    ("nestled", "soft"),
    ("Despite these challenges", "soft"),
]


@pytest.mark.parametrize(("needle", "severity"), _ARTIFACTS)
def test_provenance_and_puffery_artifacts_are_caught(needle, severity):
    res = _audit("tics.md")
    matched = [s for s in res["spans"]
               if needle.lower() in s["quote"].lower() or needle.lower() in s["context"].lower()]
    assert matched, f"{needle!r} not reported at all"
    assert any(s["severity"] == severity for s in matched), \
        f"{needle!r} reported at {[s['severity'] for s in matched]}, expected {severity}"


def test_de_ai_profile_really_does_miss_them():
    """The regression this whole consolidation exists to prevent, pinned as a fact rather than a
    claim: the de-ai profile is blind to the provenance-leak class, which is why nothing may point
    a reviewer at it alone."""
    de_ai = PA.de_ai_audit_file(str(FIXTURES / "tics.md"), ("always_flag", "cluster", "density"))
    # Compare against what the profile FLAGS (span text), not the whole payload — a stylometric
    # excerpt can quote an artifact incidentally without anyone having flagged it, which is
    # precisely the difference this test is about.
    flagged = " ".join(s["text"] for s in de_ai["spans"] if s["type"] != "style:nominalization").lower()
    for needle in ("as an ai language model", "oaicite", "plays a vital role", "i hope this helps"):
        assert needle not in flagged, f"de-ai profile unexpectedly caught {needle!r}"


# ── C6: three formats ────────────────────────────────────────────────────────
@pytest.mark.parametrize("fixture", ["tics.md", "letter.typ", "manuscript.docx"])
def test_all_three_formats_produce_spans(fixture):
    res = _audit(fixture)
    assert res["spans"], f"{fixture} produced no spans"
    assert res["n_hard"] > 0, f"{fixture} produced no hard spans"


@pytest.mark.parametrize(("fixture", "needle"), [
    ("tics.md", "rich tapestry of citations"),        # pandoc ^[...] inline footnote
    ("tics.md", "reference footnote"),                # markdown [^id]: definition
    ("letter.typ", "rich tapestry of citations"),     # Typst #footnote[...]
    ("manuscript.docx", "footnote that is itself"),   # docx word/footnotes.xml
])
def test_footnotes_are_masked_in_every_format(fixture, needle):
    res = _audit(fixture)
    for span in res["spans"]:
        assert needle.lower() not in span["context"].lower(), \
            f"{fixture}: finding landed inside a footnote — {span}"


def test_keep_footnotes_proves_masking_is_what_suppresses_them():
    masked = PA.audit_document(FIXTURES / "tics.md", mask=True)
    kept = PA.audit_document(FIXTURES / "tics.md", mask=False)
    assert len(kept["spans"]) > len(masked["spans"])
    assert "reference footnote" in _labels(kept) + " ".join(s["context"] for s in kept["spans"])


def test_em_dash_density_counts_body_prose_only(tmp_path):
    """The em-dash budget was carried over from the deleted writing-ai-smell-em-dash constraint,
    INCLUDING its exclusions. Frontmatter, fenced code, blockquotes (quoted source material) and
    HTML comments are not the author's prose, and charging their dashes to the author's budget is
    the false positive the original spent its whole `_prose_paragraphs` scanner avoiding."""
    draft = tmp_path / "dashes.md"
    draft.write_text(
        "---\ntitle: A — B — C — D — E\n---\n\n"
        "> The court said — and this matters — that the rule — as written — fails.\n\n"
        "```\ncode — with — many — em — dashes — here\n```\n\n"
        "<!-- editorial — note — with — dashes — inside -->\n\n"
        "Body text with one — dash.\n"
    )
    res = PA.audit_document(draft)
    assert not [s for s in res["spans"] if s["system"] == "em-dash"], res["spans"]

    # …and the budget still fires on real body prose.
    loud = tmp_path / "loud.md"
    loud.write_text("The rule — as written — fails, and the staff — who drafted it — knew.\n")
    assert [s for s in PA.audit_document(loud)["spans"] if s["system"] == "em-dash"]


# ── markup is not prose, and it must never reach the HARD class ──────────────
def test_typst_inline_markup_is_not_a_placeholder(tmp_path):
    """THE MEASURED FALSE POSITIVE, pinned. `#emph[First],` in a real Typst comment letter matched
    the `[Name]`-style placeholder rule — which is SEVERITY = hard, and the reviewer prompt calls a
    hard span "a provenance leak … almost never defensible". Ordinary emphasis in a regulatory
    filing was being injected into three reviewers as high-confidence evidence of AI authorship."""
    draft = tmp_path / "letter.typ"
    draft.write_text(
        "#set page(margin: 1in)\n"
        "\n"
        "There are two reasons. #emph[First], the statistic is constructed oddly.\n"
        "#emph[Second], the natural experiment says otherwise.\n"
    )
    res = PA.audit_document(draft)
    assert res["n_hard"] == 0, [s for s in res["spans"] if s["severity"] == "hard"]
    assert not [s for s in res["spans"] if "placeholder" in " ".join(s["labels"])], res["spans"]


def test_typst_neutralisation_keeps_the_prose_and_the_offsets(tmp_path):
    """Blanking the DELIMITERS and keeping the content is the point: `First` is a word the author
    wrote. It also recovers prose that was being dropped entirely — prose_extract skips a Typst
    line STARTING with `#`, so a paragraph opening `#emph[First],` never reached any scorer."""
    src = "#emph[First], the market is a rich tapestry of incentives.\n"
    out = PA.neutralize_typst_markup(src)
    assert len(out) == len(src) and out.count("\n") == src.count("\n")
    assert "First" in out and "#emph[" not in out

    draft = tmp_path / "recovered.typ"
    draft.write_text(src)
    res = PA.audit_document(draft)
    assert [s for s in res["spans"] if s["quote"].lower() == "rich tapestry"], res["spans"]


def test_typst_code_lines_are_still_skipped(tmp_path):
    """The neutraliser fires only on `#name[`, so `#let` / `#set` / `#import` stay code and stay
    skipped. Loosening that would pour a `#let` dictionary's contents into the prose scan."""
    draft = tmp_path / "code.typ"
    draft.write_text(
        '#import "@preview/letter:0.1.0": letter\n'
        "#let recipient = (\n"
        '  name: "A Delaware Court",\n'
        ")\n"
        "Real prose here.\n"
    )
    res = PA.audit_document(draft)
    assert not [s for s in res["spans"] if "Delaware" in s["context"]], res["spans"]


def test_keep_footnotes_does_not_reinstate_the_markup_false_positive(tmp_path):
    """`--keep-footnotes` debugs the raw PROSE signal. Markup was never part of that signal, so it
    is neutralised on both paths — otherwise the flag quietly brings the hard FP back."""
    draft = tmp_path / "letter.typ"
    draft.write_text("There are two reasons. #emph[First], the statistic is odd.\n")
    assert PA.audit_document(draft, mask=False)["n_hard"] == 0


def test_nested_typst_markup_closes_on_the_right_bracket():
    out = PA.neutralize_typst_markup("#emph[a #strong[b] c] tail")
    assert "#emph[" not in out and "#strong[" not in out
    assert "a" in out and "b" in out and "c" in out and out.endswith("tail")


def test_latex_markup_is_neutralised_too():
    """`.tex` has no dedicated extractor, so without this every command is scored as the author's
    own words — the same class of defect the Typst case proved."""
    out = PA.neutralize_latex_markup("\\emph{First}, see \\cite[p. 5]{smith2019} and \\begin{quote}\n")
    assert "\\emph" not in out and "\\cite" not in out and "\\begin" not in out
    assert "First" in out and "smith2019" in out  # content kept, wrapper gone


def test_unbalanced_markup_does_not_eat_the_document():
    """An opener with no closer blanks only its head. Swallowing to end-of-file would silently
    blank the rest of a draft and report it clean."""
    out = PA.neutralize_typst_markup("#emph[unclosed and then more prose about a rich tapestry")
    assert "rich tapestry" in out and "#emph" not in out


# ── severity is a property of the source table, not of this script ───────────
def test_hard_is_only_the_zero_false_positive_classes():
    res = _audit("tics.md", style="legal")
    for span in res["spans"]:
        if span["severity"] != "hard":
            continue
        assert any(
            lab.startswith(("wikipedia-chatgpt-artifacts", "wikipedia-template-artifacts",
                            "wikipedia-communication", "ai-tic·sev4", "ai-tic·sev5",
                            # `formatting·emoji` earns hard by construction, not by a corpus
                            # sweep: an emoji in a law-review draft is indefensible on its face.
                            "formatting·emoji"))
            for lab in span["labels"]), span


# ── emphasis: markup as a SIDE CHANNEL, format-agnostic ──────────────────────
# THE THREE STACKED FAILURES THIS PINS. Before v5.134.0 a Typst document could carry arbitrary
# boldface through a full writing-verify pass unremarked, because (1) the only bold rule scanned
# `<cwd>/drafts/*.md`, (2) its regex was markdown-only, and (3) neutralisation had already blanked
# the markup before any scorer ran. Fixing 1 and 2 without 3 buys nothing, which is why the spans
# are harvested from the raw text and carried alongside instead of being re-derived from prose.
#
# GOLDEN FIXTURES, NOT THE CORPUS. The FP hunt ran against `~/projects/{opv,mirror,rule611}` Typst
# sources, which live outside this repo; machine-specific paths must not enter the suite. Results
# are recorded in docs/investigations/2026-08-05_emphasis-enforcement.md.
_BOLD_LEAD_SOURCES = [
    (".typ", "#strong[The objection.] A five percent stake could leverage mirror voting.\n"),
    (".tex", "\\textbf{The objection.} A five percent stake could leverage mirror voting.\n"),
    (".md", "**The objection.** A five percent stake could leverage mirror voting.\n"),
]


@pytest.mark.parametrize(("suffix", "src"), _BOLD_LEAD_SOURCES)
def test_bold_lead_is_flagged_in_every_text_format(tmp_path, suffix, src):
    draft = tmp_path / f"lead{suffix}"
    draft.write_text(src)
    res = PA.audit_document(draft)
    hits = [s for s in res["spans"] if s["system"] == "emphasis"]
    assert any("bold-lead" in lab for s in hits for lab in s["labels"]), res["spans"]
    assert hits[0]["line"] == 1 and hits[0]["col"] == 1, hits


@pytest.mark.parametrize(("suffix", "src"), [
    (".typ", "+ #strong[Market mirroring.] The block votes For and Against in proportion.\n"),
    (".md", "- **Market mirroring.** The block votes For and Against in proportion.\n"),
    (".md", "1. **Market mirroring.** The block votes For and Against in proportion.\n"),
])
def test_list_items_are_exempt_from_bold_lead(tmp_path, suffix, src):
    """APPROVED DECISION, and a measured one. mirror/paper/typst/body.typ:161-169 is a numbered
    scenario list whose items open `+ #strong[Market mirroring.]`. A numbered list of defined
    scenarios is not an inline-header paragraph, and flagging it would make the rule unusable on
    the one local source that carries the most emphasis."""
    draft = tmp_path / f"list{suffix}"
    draft.write_text(src)
    res = PA.audit_document(draft)
    assert not [s for s in res["spans"] if "bold-lead" in " ".join(s["labels"])], res["spans"]


def test_exhibit_captions_are_exempt_from_bold_lead(tmp_path):
    """FOUND BY THE FP HUNT: `#strong[Table 1:] Headline reform comparison…` accounted for ALL
    FIVE out-of-table bold-lead hits in mirror/paper/typst/body.typ. A caption label is not an
    inline header, and it is excluded by shape rather than by lowering the bar."""
    draft = tmp_path / "caption.typ"
    draft.write_text("#strong[Table 1:] Headline reform comparison across four block levels\n"
                     "\n"
                     "#strong[Figure 2.] Mirror pro-rata flips by vote category\n")
    res = PA.audit_document(draft)
    assert not [s for s in res["spans"] if "bold-lead" in " ".join(s["labels"])], res["spans"]


def test_table_cells_are_exempt_from_every_bold_rule(tmp_path):
    """NOT AN OPTIMISATION — the thing that makes the bold rules viable. mirror's 258 `#strong[]`
    spans are overwhelmingly table header cells; without this a correctly formatted results table
    reads as bold saturation."""
    draft = tmp_path / "table.typ"
    draft.write_text(
        "#table(\n"
        "  columns: 3,\n"
        "  #strong[Items], #strong[Flips], #strong[(%)],\n"
        "  [Say on pay], #strong[2,070], #strong[0.40%],\n"
        ")\n")
    res = PA.audit_document(draft)
    assert not [s for s in res["spans"] if s["system"] == "emphasis"], res["spans"]


@pytest.mark.parametrize(("suffix", "src"), [
    (".typ", "The market saw #strong[546,088] trades and #strong[63% more] volume overall.\n"),
    (".tex", "The market saw \\textbf{546,088} trades and \\textbf{63\\% more} volume.\n"),
    (".md", "The market saw **546,088** trades and **63% more** volume overall today.\n"),
])
def test_bold_on_a_bare_number_is_flagged_in_every_text_format(tmp_path, suffix, src):
    draft = tmp_path / f"num{suffix}"
    draft.write_text(src)
    res = PA.audit_document(draft)
    quoted = {s["quote"] for s in res["spans"]
              if "bold-bare-number" in " ".join(s["labels"])}
    assert "546,088" in quoted, res["spans"]


def test_bold_on_a_claim_is_not_a_bare_number(tmp_path):
    """The rule is `emphasise the claim, not the digits`, so the claim itself must pass."""
    draft = tmp_path / "claim.typ"
    draft.write_text("The market saw #strong[546,088 trades] under the proposed rule.\n")
    res = PA.audit_document(draft)
    assert not [s for s in res["spans"] if "bold-bare-number" in " ".join(s["labels"])], res["spans"]


def test_bold_density_needs_a_document(tmp_path):
    """`mirror/paper/typst/style.typ` is a template with one prose word in it. One bold span over
    one word is 1,000 per 1,000 — an arithmetic artifact, not saturation."""
    draft = tmp_path / "style.typ"
    draft.write_text("#let x = 1\n#strong[Note]\n")
    res = PA.audit_document(draft)
    assert not [s for s in res["spans"] if "bold-density" in " ".join(s["labels"])], res["spans"]


def test_bold_density_fires_over_the_budget(tmp_path):
    draft = tmp_path / "loud.typ"
    body = " ".join(f"Word{i}" for i in range(400))
    draft.write_text(body + "\n\n" + "\n".join(
        f"Sentence {i} reports #strong[a finding] about the market." for i in range(20)))
    res = PA.audit_document(draft)
    hits = [s for s in res["spans"] if "bold-density" in " ".join(s["labels"])]
    assert hits and hits[0]["line"] == 0, res["spans"]


def test_strong_inside_a_typst_footnote_is_never_collected(tmp_path):
    """Footnote masking runs FIRST, for the same reason it runs first before neutralisation: a
    finding must never land inside a note."""
    draft = tmp_path / "fn.typ"
    draft.write_text("The rule applies.#footnote[See #strong[546,088] trades in the record.]\n")
    _, _, spans = PA.extract_lines(draft)
    assert not spans, spans


def test_emphasis_collection_survives_neutralisation(tmp_path):
    """The regression the whole side-channel design exists to prevent: the scorers still see
    neutralised text (markup blanked, prose kept), and the emphasis spans exist anyway."""
    draft = tmp_path / "both.typ"
    draft.write_text("The market saw #strong[546,088] trades and #emph[substantial] growth.\n")
    lines, masked, spans = PA.extract_lines(draft)
    assert "#strong[" not in masked and "546,088" in masked   # neutralisation unchanged
    assert [s["kind"] for s in spans] == ["strong", "emph"]
    assert spans[0]["text"] == "546,088"


def test_emphasis_does_not_reinstate_the_v5127_hard_false_positive(tmp_path):
    """PINNED. `#emph[First],` matched wikipedia-template-artifacts' `[Name]` placeholder rule — a
    HARD span the reviewer prompt calls "almost never defensible". Harvesting emphasis must not
    bring it back by any route, and emphasis findings are soft besides."""
    draft = tmp_path / "letter.typ"
    draft.write_text(
        "There are two reasons. #emph[First], the statistic is constructed oddly.\n"
        "#emph[Second], the natural experiment says otherwise.\n")
    res = PA.audit_document(draft)
    assert res["n_hard"] == 0, [s for s in res["spans"] if s["severity"] == "hard"]
    assert not [s for s in res["spans"] if "placeholder" in " ".join(s["labels"])], res["spans"]
    assert all(s["severity"] == "soft" for s in res["spans"] if s["system"] == "emphasis")


def test_docx_emphasis_is_deferred_not_silently_wrong(tmp_path):
    """`.docx` bold runs are out of scope, and the contract says so explicitly rather than
    implying it: no emphasis spans, no crash."""
    lines, masked, spans = PA.extract_lines(_DOCX)
    assert masked is None and spans == [] and lines


# ── hard-wrapped paragraphs: the rule turns on the READER, not the extension ──
# THE OBSERVED PROBLEM. Prose in the owner's Obsidian notes and emails was arriving wrapped at ~80
# columns, because nearly every file an agent reads — SKILL.md, agent bodies, code comments — is
# wrapped, so wrapped text is what prose looks like to it. Both readers soft-wrap, so the breaks
# land mid-sentence at the reader's width and a one-word edit re-wraps the paragraph.
_WRAPPED_EMAIL = (
    "Thanks for sending the revised term sheet over the weekend. I read it on the plane and I\n"
    "think the economics are close to where we left them in June, but the indemnity cap still\n"
    "reads as though it survives the escrow release, which was not what we agreed to on the\n"
    "call. I have marked the two clauses that matter and left the rest alone.\n"
)


def _wrap_spans(res: dict) -> list[dict]:
    return [s for s in res["spans"] if any("hard-wrap" in lab for lab in s["labels"])]


def test_hard_wrapped_paragraph_is_flagged(tmp_path):
    draft = tmp_path / "reply.md"
    draft.write_text(_WRAPPED_EMAIL)
    spans = _wrap_spans(PA.audit_document(draft))
    assert len(spans) == 1, spans
    assert spans[0]["severity"] == "soft"          # a formatting tell, not a corpus-gated class
    assert spans[0]["line"] == 1


def test_one_line_paragraphs_are_silent(tmp_path):
    """The shape a hard wrap makes is one prose written one-paragraph-per-line never makes."""
    draft = tmp_path / "reply.md"
    draft.write_text(_WRAPPED_EMAIL.replace("\n", " ").strip() + "\n\n"
                     + "Let me know whether Sarah can join Thursday. If she cannot, I would rather "
                       "push the whole conversation to the following week than run it without her, "
                       "because she owns the escrow mechanics.\n")
    assert _wrap_spans(PA.audit_document(draft)) == []


def test_a_wrapped_bulleted_list_is_not_a_wrapped_paragraph(tmp_path):
    """A wrapped list item is a different thing — its continuation lines are indented, and the
    marker line is not running prose. Flagging these would fire on every well-formed list."""
    draft = tmp_path / "list.md"
    draft.write_text(
        "- Thanks for sending the revised term sheet over the weekend, which I read on\n"
        "  the plane and thought was close to where we left it in June before the call\n"
        "- The indemnity cap still reads as though it survives the escrow release, and\n"
        "  that was not what the parties agreed to on the call last Thursday afternoon\n"
        "- I have marked the two clauses that matter here and have left the rest alone\n"
    )
    assert _wrap_spans(PA.audit_document(draft)) == []


def test_a_fenced_code_block_is_not_a_wrapped_paragraph(tmp_path):
    draft = tmp_path / "fence.md"
    draft.write_text(
        "Here is the command.\n\n"
        "```\n"
        "uv run --with lxml --with pyyaml python3 scripts/prose-audit.py --json --style\n"
        "  general drafts/reply.md | jq '.spans[] | select(.severity == \"hard\") | .id'\n"
        "cat scripts/prose-audit.py | rg 'formatting.hard-wrap' --line-number --color\n"
        "```\n"
    )
    assert _wrap_spans(PA.audit_document(draft)) == []


def test_wrapped_source_files_are_exempt_and_the_exemption_is_load_bearing():
    """NON-VACUITY. `skills/writing-general/SKILL.md` is legitimately wrapped at ~100 columns and
    MUST NOT be flagged when audited as source — a rule that fires on the register's own files is
    worse than no rule. This pins that the exemption is what suppresses it, not the shape test:
    the raw shape scanner finds runs in that file, and the audit still reports none."""
    skill = REPO_ROOT / "skills" / "writing-general" / "SKILL.md"
    text = skill.read_text(encoding="utf-8")
    assert PA.is_fixed_width_source(skill, text)
    assert PA._hard_wrap_hits(text), "shape scanner must find the wrap runs it is being spared for"
    assert _wrap_spans(PA.audit_document(skill)) == []


@pytest.mark.parametrize("name", ["draft.typ", "draft.tex", "SKILL.md", "CLAUDE.md"])
def test_fixed_width_readers_are_exempt_by_name_and_suffix(tmp_path, name):
    draft = tmp_path / name
    draft.write_text(_WRAPPED_EMAIL)
    assert _wrap_spans(PA.audit_document(draft)) == []


def test_obsidian_frontmatter_does_not_buy_an_exemption(tmp_path):
    """A note's `tags:`/`aliases:` frontmatter is not skill/agent frontmatter, and an Obsidian
    note is exactly the soft-wrapping reader this rule exists for."""
    draft = tmp_path / "note.md"
    draft.write_text("---\ntags: [deals]\naliases: [term sheet]\n---\n\n" + _WRAPPED_EMAIL)
    assert _wrap_spans(PA.audit_document(draft))


# ── emojis: the one hard rule here ───────────────────────────────────────────
def test_emoji_in_prose_is_hard(tmp_path):
    draft = tmp_path / "emoji.md"
    draft.write_text("The agency responded quickly 🚨 and the staff agreed.\n")
    res = PA.audit_document(draft)
    hits = [s for s in res["spans"] if s["system"] == "formatting"]
    assert hits and hits[0]["severity"] == "hard", res["spans"]
    assert hits[0]["line"] == 1


def test_emoji_inside_a_fence_or_quote_is_clean(tmp_path):
    """Same exclusions as the em-dash budget: a fenced code block and a quoted source are not the
    author's prose, and a HARD rule may not fire on them."""
    draft = tmp_path / "fenced.md"
    draft.write_text("```\nprint('🚨 alert')\n```\n\n> The filing said 🚨 loudly.\n\nBody text.\n")
    res = PA.audit_document(draft)
    assert not [s for s in res["spans"] if s["system"] == "formatting"], res["spans"]


@pytest.mark.parametrize("ch", ["×", "—", "§", "†", "‡", "✓", "✔"])
def test_typographic_characters_are_not_emojis(tmp_path, ch):
    """A `hard` rule may not fire on a multiplication sign, an em dash, a section mark, a dagger
    or a checkmark in a comparison table. The VS16 emoji-presentation forms still match."""
    draft = tmp_path / "typo.md"
    draft.write_text(f"The ratio is 1.60{ch} across every specification in the table.\n")
    res = PA.audit_document(draft)
    assert not [s for s in res["spans"] if s["system"] == "formatting"], res["spans"]


def test_emoji_in_a_slide_deck_is_soft_not_hard(tmp_path):
    """A deck is not a draft and emoji in one are deliberate. The hook refuses to lint a deck at
    all; this covers the case it cannot — auditing a deck ON PURPOSE from the CLI. The finding
    survives (you asked for the audit) but may not block a gate."""
    deck = tmp_path / "08.typ"
    deck.write_text('#slide(title: "Insider trading")[\n  The rule bites 🚨 here.\n]\n')
    res = PA.audit_document(deck)
    hits = [s for s in res["spans"] if s["system"] == "formatting"]
    assert hits, res["spans"]
    assert hits[0]["severity"] == "soft", hits
    assert res["n_hard"] == 0, [s for s in res["spans"] if s["severity"] == "hard"]

    # …and the identical content outside a deck is still hard.
    draft = tmp_path / "letter.typ"
    draft.write_text("#set page(margin: 1in)\n\nThe rule bites 🚨 here.\n")
    assert [s for s in PA.audit_document(draft)["spans"]
            if s["system"] == "formatting" and s["severity"] == "hard"]


def test_deck_detection_matches_the_hooks_rules(tmp_path):
    """`is_deck` mirrors `isTypDeck` in hooks/writing-prose-check.ts. The cross-LANGUAGE agreement
    is pinned in tests/writing-prose-check.test.mjs; this pins the Python side's own rules."""
    slides = tmp_path / "slides" / "03-security"
    slides.mkdir(parents=True)
    by_dir = slides / "08.typ"
    by_dir.write_text("Dear Professor,\n")            # no marker at all
    assert PA.is_deck(by_dir)
    for marker in ('#import "@preview/touying:0.5.0": *\n',
                   '#import "@preview/polylux:0.3.1": *\n',
                   '#slide(title: "x")[ y ]\n'):
        f = tmp_path / "theme.typ"
        f.write_text(marker)
        assert PA.is_deck(f), marker
    letter = tmp_path / "letter.typ"
    letter.write_text("#set page(margin: 1in)\nDear Professor,\nSincerely.\n")
    assert not PA.is_deck(letter)
    md = tmp_path / "slides" / "notes.md"
    md.write_text("#slide(\n")
    assert not PA.is_deck(md), "only .typ can be a deck"


# ── corpus-gated tics: the BOUNDARY is the assertion worth having ────────────
# Both of these shipped on 2026-08-05 after an FP-hunt over 14,294,148 sentences (8.73M finance +
# 5.56M law-review). For each, the corpus proved a NEAR-MISS is genuine human scholarship, and the
# negative case below is that near-miss. A positive-only test would pass just as well with a rule
# broad enough to be useless.
#
#   rule-bites        the VERB is unattested (1/14.29M, and that hit is a cited FT headline in a
#                     footnote). The NOUN is human — 46 hits, including a law review article title,
#                     "Do the SEC's New Rating Agency Rules Have Any Bite?"
#   sharpest-version  0/14.29M. But all four hits of `<superlative> version of` are "the STRONGEST
#                     version of", and `the sharpest <noun>` at large is 86 hits. The word is
#                     ordinary; the collocation is the tell.
@pytest.mark.parametrize(("verdict", "sentence"), [
    # Both FIRE cases are verbatim from ~/projects/mirror/paper/typst/body-src.typ (:640 and :19),
    # which passed a full writing-verify with neither flagged.
    ("fire",  "the reform should bite hardest there"),
    ("fire",  "The sharpest version of the objection names an actor"),
    ("fire",  "the rule bites in exactly these cases"),
    # The participle walked through a finite-verb-only pattern in a live draft ("a case where the
    # rule could have bitten but did not"). Subject-anchored, 0/14,294,148 --exact. The unanchored
    # auxiliary form stays out: `(would|could|...) (have) bit(e|ten)` is 1.80/M in law -- cited
    # titles ("Bitcoin Will Bite the Dust") and one literal snake -- which the last two negatives
    # below pin down.
    ("fire",  "a case where the rule could have bitten but did not"),
    ("fire",  "the statute has been biting hardest at the margin"),
    ("clean", "If it had been a snake, it would have bitten us"),
    ("clean", "See Bitcoin Will Bite the Dust, 35 Cato J 357, 359 (2015)"),
    ("clean", "the restriction has more bite in periods of high uncertainty"),
    ("clean", "Reputational sanctions always have more bite, however"),
    ("clean", "the strongest version of the ECMH is hard to defend"),
    ("clean", "The sharpest decline occurred between 1976 and 1978"),
])
def test_bite_and_sharpest_version_respect_the_corpus_boundary(tmp_path, verdict, sentence):
    draft = tmp_path / f"tic-{abs(hash(sentence))}.md"
    draft.write_text(sentence + "\n")
    labels = _labels(PA.audit_document(draft))
    hit = "rule-bites" in labels or "sharpest-version" in labels
    assert hit == (verdict == "fire"), f"{sentence!r} -> {labels}"


# data-grain: 0/14,294,148 over both halves. This one is an ETL-vocabulary leak rather than a
# chatbot tic -- "the grain of the table" is dbt/warehouse jargon, and the two corpus hits for
# `at the ... grain` are literal cereal ("grain futures regulation", "Tokyo Grain Exchange").
# Humans writing the same idea reach for `unit of observation` (55/M in finance) or `one
# observation per` (21/M). The negatives below are the ordinary English senses the rule must
# never touch, plus the comma boundary that an earlier `\S{0,2}` draft of the pattern crossed.
@pytest.mark.parametrize(("verdict", "sentence"), [
    ("fire",  "The panel's grain is the agenda item crossed with the ownership block"),
    ("fire",  "An undeduplicated lookup would change the data's grain"),
    ("fire",  "We report results at the grain of the panel rather than the meeting"),
    ("clean", "That claim should be taken with a grain of salt"),
    ("clean", "The holding cuts against the grain of the earlier cases"),
    ("clean", "in March 1935 at the time grain futures regulation was being debated"),
    ("clean", "Note: In this table, grain trade includes cotton trade and brokerage firms"),
])
def test_data_grain_leaves_the_ordinary_senses_alone(tmp_path, verdict, sentence):
    draft = tmp_path / f"grain-{abs(hash(sentence))}.md"
    draft.write_text(sentence + "\n")
    labels = _labels(PA.audit_document(draft))
    assert ("data-grain" in labels) == (verdict == "fire"), f"{sentence!r} -> {labels}"


# sharpest-cut: companion to sharpest-version, same shape. `the sharpest <anything>` is thoroughly
# human (5.67/M) and `sharpest contrast|distinction BETWEEN X and Y` is the attested form -- all
# four corpus hits take that template ("the sharpest contrast between persistent and transitory
# losses"). What is unattested is the superlative pointed at a data cut: `sharpest cut` is 0, and
# `<superlative> <cut|contrast|divide> in the <table|data|sample>` is 0/14,294,148. Humans reach
# for `most striking` (28.5/M) or `largest difference` (5.0/M). The negatives below are the human
# template and the ordinary concrete-quantity superlative the rule must not touch.
@pytest.mark.parametrize(("verdict", "sentence"), [
    ("fire",  "The thirty-three-to-one ratio is the sharpest cut in the table"),
    ("fire",  "That is the starkest contrast in the data we report"),
    ("clean", "Panel A shows the sharpest contrast between persistent and transitory losses"),
    ("clean", "This provides the sharpest distinction between the bonding hypothesis and others"),
    ("clean", "The sharpest decline occurred between 1976 and 1978"),
    ("clean", "The most striking difference in the table is the turnout gradient"),
])
def test_sharpest_cut_spares_the_human_template(tmp_path, verdict, sentence):
    draft = tmp_path / f"scut-{abs(hash(sentence))}.md"
    draft.write_text(sentence + "\n")
    labels = _labels(PA.audit_document(draft))
    assert ("sharpest-cut" in labels) == (verdict == "fire"), f"{sentence!r} -> {labels}"


@pytest.mark.parametrize(("verdict", "sentence"), [
    ("fire",  "The limits bound all of it, and the analysis cannot escape them"),
    ("fire",  "Those constraints bound the analysis in ways the paper never confronts"),
    # `bound` is 790/M in BOTH halves — the word is useless as a rule and only the OBJECT
    # discriminates. Obligating a legal actor is core legal vocabulary (7 hits, 1.26/M in law
    # reviews); a rule that fired on these would hit "the rule bound the agency" in any
    # securities-law draft, which is the whole failure mode this gate exists to prevent.
    ("clean", "Interpretive statements bound the agency, the Commission argued"),
    ("clean", "The earlier Missouri decision bound the court to deny the rule"),
    ("clean", "The parties are bound by the indenture"),
    ("clean", "We report the upper bound of the estimate"),
])
def test_bound_fires_on_abstractions_not_on_obligated_parties(tmp_path, verdict, sentence):
    """`bound-abstraction`: 0/14,294,148 for the transitive-against-an-abstraction sense.

    Third instance of the same shape as rule-bites and sharpest-version — the word is ordinary
    and the construction is the tell. Probing the family rather than the phrase is what found it."""
    draft = tmp_path / f"bound-{abs(hash(sentence))}.md"
    draft.write_text(sentence + "\n")
    labels = _labels(PA.audit_document(draft))
    assert ("bound-abstraction" in labels) == (verdict == "fire"), f"{sentence!r} -> {labels}"


def test_the_new_tics_are_soft_not_hard():
    """sev>=4 is `hard` and blocks a gate. Neither of these earned that: `rule-bites` is a legal
    idiom in a register the control corpus under-covers, and `sharpest-version` sits inside a
    family the corpus proved human."""
    import re as _re
    mod = PA._load_module(PA.SCORED_TICS)
    for _, label in mod._TIC_PATTERNS:
        if any(k in label for k in ("rule-bites", "sharpest-version", "bound-abstraction")):
            sev = int(_re.search(r"sev(\d)", label).group(1))
            assert sev <= 3, label


# ── false precision: summary prose is not the exhibit ────────────────────────
# EVERY "fire" case below is verbatim from a law-review manuscript edit (mirror/paper/typst), and
# every one of them was CHANGED: "a rate of 1.3771 percent" -> "about one and a half percent";
# "roughly ten times the 2.7361 percent rate" -> "…the abstention-wide rate"; "6,612 of 575,553
# testable items --- 1.15 percent" -> "about one percent of testable items"; "85.63 percent of the
# testable universe" -> "roughly six in seven"; "the 28.3328 percent figure" -> "that figure".
#
# THE NEGATIVES ARE THE RULE. A digit-heavy legal draft is mostly cites, years, dockets, versions
# and money, and a rule that cannot tell those from a summary statistic is unusable on exactly the
# documents this one exists for. Measured on mirror/paper/typst/body-src.typ: 12 hits, all in Part
# I/II/III/IV summary prose, and ZERO on its 1,519 `table.cell(align: right)[…]` lines.
def _fp_labels(draft: Path) -> str:
    return " ".join(lab for s in PA.audit_document(draft)["spans"] for lab in s["labels"])


@pytest.mark.parametrize("sentence", [
    "The block flips at a rate of 1.3771 percent across the frozen panel today.",
    "That is roughly ten times the 2.7361 percent rate reported in the appendix.",
    "We find 6,612 of 575,553 testable items --- 1.15 percent --- fall below it.",
    "The sample covers 85.63 percent of the testable universe of items today.",
    "Compare the 28.3328 percent figure from the earlier draft of this paper.",
])
def test_false_precision_fires_on_summary_prose(tmp_path, sentence):
    draft = tmp_path / f"fp-{abs(hash(sentence))}.md"
    draft.write_text(sentence + "\n")
    assert "false_precision" in _fp_labels(draft), sentence


@pytest.mark.parametrize("sentence", [
    # years — no decimal point exists to over-specify
    "The rule was adopted in 1976 and amended again in 2005 by the Commission.",
    # statutory / rule / section / order / bill cites
    "See Rule 14a-8 and 17 C.F.R. § 240.14a-101 for the operative text here.",
    "Executive Order 14,366 and S. 1670 both bear on the same question here.",
    "The DGCL 216 default quorum applies unless the bylaws provide otherwise.",
    "The disclosure obligation arises under § 208A of the amended statute.",
    # version numbers and dotted identifiers
    "We ran this under Python 3.11.4 with the touying 0.5.0 template package.",
    # money, where the cents are the point
    "The filing fee was $1,234.56 and the per-share price was $12.75 that day.",
    # page / line / footnote locators
    "See supra note 203 at 1055 for the full discussion of this point today.",
    # under the thresholds: a bare two-decimal figure and a one-decimal percentage
    "The mean turnout ratio was 1.60 across every specification in the panel.",
    "Say-on-pay items flip at 0.4 percent under the market-mirroring scenario.",
])
def test_false_precision_does_not_fire_on_legitimate_digits(tmp_path, sentence):
    draft = tmp_path / f"fp-neg-{abs(hash(sentence))}.md"
    draft.write_text(sentence + "\n")
    assert "false_precision" not in _fp_labels(draft), sentence


def test_false_precision_ignores_exhibits_and_quoted_material(tmp_path):
    """EXACT FIGURES NEXT TO THE EXHIBIT ARE LEGITIMATE — that is the whole shape of the rule.
    The Typst `table.cell` case is the load-bearing one: body-src.typ carries 1,519 of them, and a
    rule that flags a correctly formatted results table is worse than no rule."""
    typ = tmp_path / "exhibit.typ"
    typ.write_text(
        "#figure(\n"
        "  align(center)[#table(\n"
        "    columns: 2,\n"
        "    table.cell(align: right)[0.3952], table.cell(align: right)[2.7361],\n"
        "    table.cell(align: right)[17.34], table.cell(align: right)[85.63%],\n"
        "  )]\n"
        ")\n")
    assert "false_precision" not in _fp_labels(typ), typ.read_text()

    md = tmp_path / "exhibit.md"
    md.write_text(
        "| Scenario | Rate |\n"
        "|---|---|\n"
        "| Market mirroring | 0.3952 percent |\n"
        "\n"
        "```\nflip_rate = 1.3771  # percent of testable items in the frozen panel\n```\n"
        "\n"
        "> The staff reported a flip rate of 2.7361 percent across all items.\n")
    assert "false_precision" not in _fp_labels(md), md.read_text()


def test_false_precision_never_lands_in_a_footnote(tmp_path):
    """Same non-negotiable every other system here obeys: a finding must never land in a note."""
    typ = tmp_path / "fn.typ"
    typ.write_text("The reform changes few outcomes.#footnote[Precisely 1.3771 percent of them.]\n")
    assert "false_precision" not in _fp_labels(typ), typ.read_text()

    md = tmp_path / "fn.md"
    md.write_text("The reform changes few outcomes.^[Precisely 1.3771 percent of them here.]\n"
                  "\n[^a]: The abstention-wide rate is 2.7361 percent of testable items.\n")
    assert "false_precision" not in _fp_labels(md), md.read_text()


def test_false_precision_is_soft(tmp_path):
    """`hard` is reserved for the zero-false-positive provenance classes. A rounded figure is a
    style preference with a defensible exception (an exact value beside its exhibit), so this one
    may report but may never block a gate."""
    draft = tmp_path / "fp.md"
    draft.write_text("The block flips at a rate of 1.3771 percent across the frozen panel.\n")
    res = PA.audit_document(draft)
    hits = [s for s in res["spans"] if any("false_precision" in lab for lab in s["labels"])]
    assert hits and all(s["severity"] == "soft" for s in hits), res["spans"]
    assert res["n_hard"] == 0, [s for s in res["spans"] if s["severity"] == "hard"]


# ── the CLI contract the hook and the reviewers depend on ────────────────────
def test_cli_json_and_exit_code():
    proc = subprocess.run(
        [sys.executable, str(AUDIT_PATH), "--json", "--style", "legal", str(FIXTURES / "tics.md")],
        capture_output=True, text=True, check=False)
    assert proc.returncode == 1, proc.stderr           # hard spans present
    payload = json.loads(proc.stdout)
    assert payload["spans"][0]["id"] == "S001"
    assert {"id", "line", "col", "system", "labels", "severity", "quote", "replace_with"} \
        <= set(payload["spans"][0])


def test_cli_exits_zero_on_soft_only_prose(tmp_path):
    """Only `hard` may block a gate, and the exit code says so."""
    draft = tmp_path / "soft.md"
    draft.write_text("Despite these challenges, the agency proceeded with the rule.\n")
    proc = subprocess.run(
        [sys.executable, str(AUDIT_PATH), "--json", str(draft)],
        capture_output=True, text=True, check=False)
    assert proc.returncode == 0, proc.stdout
    payload = json.loads(proc.stdout)
    assert payload["spans"] and payload["n_hard"] == 0


# start-with-abstraction: the imperative opener is thoroughly human -- sentence-initial
# `Start|Begin with` is 30/14,294,148 (2.5/M finance, 1.4/M law), well over the rate line. What is
# unattested is the wh-complement: humans start with a THING ("Start with an index fund", "Start
# with the case of MZ twins"), never with a meta-move about the argument. `(Start|Begin) with
# (what|why|how|who|the question|the premise|...)` is 0/14,294,148 over both halves. The negatives
# below are the attested concrete form the rule must never touch.
@pytest.mark.parametrize(("verdict", "sentence"), [
    ("fire",  "Start with what the analysis actually does"),
    ("fire",  "Begin with the question the release never asks"),
    ("fire",  "Start with why the tiers run on price"),
    ("clean", "Start with an index fund"),
    ("clean", "Start with the case of MZ twins"),
    ("clean", "Begin with the optimal contract and work backwards"),
])
def test_start_with_abstraction_leaves_the_concrete_opener_alone(tmp_path, verdict, sentence):
    draft = tmp_path / f"startwith-{abs(hash(sentence))}.md"
    draft.write_text(sentence + "\n")
    labels = _labels(PA.audit_document(draft))
    assert ("start-with-abstraction" in labels) == (verdict == "fire"), f"{sentence!r} -> {labels}"


if __name__ == "__main__":
    sys.exit(pytest.main([__file__, "-q"]))


# ── ai-tic·sev2·the-x-is-the-y ─────────────────────────────────────
# The tic is announcing that something IS the argument/payoff/point in place of stating it.
# Corpus result behind the rule: 0 hits / 14,294,148 sentences of law + finance prose.
#
# THE NEGATIVE IS THE POINT OF THIS CASE. The broad frame `is the problem` measured 35.61/M —
# 509 human hits — so the rule is deliberately narrowed to the META-DISCOURSE nouns. A rule that
# fires on "the benefits principle is the problem." is a linter that fires on real scholarship.
# Do not widen the pattern without re-running scripts/fp-check.sh --exact against both corpus halves.

def _labels_for(text: str) -> str:
    with tempfile.TemporaryDirectory() as d:
        p = Path(d) / "t.md"
        p.write_text(text, encoding="utf-8")
        r = subprocess.run(
            ["uv", "run", "--with", "lxml", "--with", "pyyaml", "python3",
             str(AUDIT_PATH), "--json", str(p)],
            capture_output=True, text=True,
        )
        assert r.returncode in (0, 1), f"audit failed ({r.returncode}): {r.stderr[:400]}"
        spans = json.loads(r.stdout).get("spans", [])
    return " ".join(str(s.get("labels") or s.get("label", "")) for s in spans)


def test_announce_is_the_argument_fires():
    assert "the-x-is-the-y" in _labels_for("The selection is the argument.")


def test_announce_is_the_argument_spares_the_human_near_miss():
    """`is the problem` is human at 35.61/M — 509 hits. The rule must not reach it."""
    assert "the-x-is-the-y" not in _labels_for(
        "the benefits principle is the problem."
    )


def test_abstract_noun_gate_fires():
    assert "abstract-noun-gate" in _labels_for(
        "The liability gate is what the statute actually moved."
    )


def test_abstract_noun_gate_spares_the_hedge_fund_term_of_art():
    """`a gate on redemptions` is a live finance term; bare `gate` runs 90.74/M. Neither is reached."""
    assert "abstract-noun-gate" not in _labels_for(
        "The fund manager has the right to impose a gate on redemptions."
    )
    assert "abstract-noun-gate" not in _labels_for(
        "The ratio gates whether the effect appears at all."
    )
